#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

## Monitors
bspc monitor -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap          12

## Configs
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

## Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a lutris state=floating
bspc rule -a mpv state=fullscreen

$HOME/.config/bspwm/autostart.sh &
